[package]
name = "{{project-name}}"
version = "0.0.1"
edition = "2021"
authors = ["{{authors}}"]
description = "{{description}}"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]